<?php
$local_pages=array("/home",
"/goto","___END");
$local_pages_img=array(""._HTML_RES_."/icon/site/home.png",
""._HTML_RES_."/icon/site/goto.png");
$local_pages_title=array("小屋",
"去往");
$other_pages=array("https://blog.josephz.top",
"https://pan.josephz.top","___END");
$other_pages_img=array(""._HTML_RES_."/icon/site/blog.png",
""._HTML_RES_."/icon/site/pan.png");
$other_pages_title=array("博客",
"云盘");
$home_pages_local=array("search",
"time",
"projects",
"videos","___END");
$home_pages_local_title=array("搜索",
"时间",
"项目",
"视频");
$home_pages_local_intro=array("search",
"time",
"projects",
"videos");
$home_pages_other=array("https://doc.josephz.top",
"https://mc.josephz.top","___END");
$home_pages_other_title=array("文档",
"休闲");
$home_pages_other_intro=array("docs",
"relax");

?>